name: CI
on: [push, pull_request]
jobs:
  build:
    ## Runs on Mac because Mac is currently what I use to generate the e2e test screenshots locally
    ## Ideally I would be generating them in a Linux container but this is convenient for now
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Install app dependencies
        run: bun install
      - name: Build app (build, lint, run unit tests)
        run: bun run build:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Install Playwright dependencies
        run: bunx playwright install --with-deps
      - name: Run Playwright E2E tests
        run: npx playwright test
        env:
          CI: "1"
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
