name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run linter
        run: bun lint
      - name: Run tests
        run: bun jest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
