name: CI
on: [push, pull_request, workflow_call]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
  build:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: bun run build
  # lint:
  #   needs: [install]
  #   steps:
  #     - name: Run linter
  #       run: bun lint
  #     - name: Run tests
  #       run: bun jest --coverage
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v3
  #       env:
  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  #       with:
  #         files: ./coverage/coverage-final.json
