name: Live E2E Tests
on:
  deployment_status:
jobs:
  e2e-live:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Install test dependencies
        run: bun install
      - name: Install Playwright dependencies
        run: bun playwright install --with-deps
      - name: Run tests
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          CI: "1"
        run: |
          echo $BASE_URL
          bun playwright test
